export enum BeersActionTypes {
  BEERS_DATA_FETCH = "BEERS_DATA_FETCH",
  BEERS_DATA_SET = "BEERS_DATA_SET",
  BEERS_ACTIVE_ITEM_SET = "BEERS_ACTIVE_ITEM_SET",
  BEERS_DATA_CLEAR = "BEERS_DATA_CLEAR",
};
